back end/project/app/urls.py
from django.urls import path , include
from . import views
app_name='app'
urlpatterns = [
    path('', views.home , name='home'),
    path('products/', views.products , name='products'),

    path('<str:slug>', views.details, name='details'),

    path('blogs/', views.blogs , name='blogs'),

    path('blogs/<str:slug>', views.blog, name='blog'),

]

back end/project/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]
urlpatterns += [path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file")]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back end/project/app/models.py
from django.db import models
import os
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.

def image_upload(instance, filename):
    name, extension = os.path.splitext(filename)
    return f"pro/{instance.id}{extension}"

class Product(models.Model):
    title = models.CharField(max_length=50 , verbose_name='إسم المنتج:')
    price = models.IntegerField(verbose_name="السعر")
    img1 = models.ImageField(upload_to=image_upload, verbose_name="الصورة الرئيسية")
    img2 = models.ImageField(upload_to=image_upload, verbose_name="الصورة2", null=True, blank=True)
    img3 = models.ImageField(upload_to=image_upload, verbose_name="الصورة3", null=True, blank=True)
    # quantity = models.IntegerField(verbose_name="الكمية")
    details = CKEditor5Field(blank=True, null=True, verbose_name="الوصف", config_name='extends')
    active = models.BooleanField(default=True)
    slug = models.SlugField(null=True, blank=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)
    

    def __str__(self):
        return self.title
    


def image_upload_cat(instance, filename):
    name, extension = os.path.splitext(filename)
    return f"cat/{instance.id}{extension}"
    
class Blog(models.Model):
    name = models.CharField(max_length=50 , verbose_name='إسم المقال:')
    author = models.CharField(max_length=50 , verbose_name='إسم الكاتب:')
    img = models.ImageField(upload_to=image_upload_cat, verbose_name="الصورة:")
    details = CKEditor5Field(blank=True, null=True, verbose_name="الوصف", config_name='extends')
    published_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    slug = models.SlugField(null=True, blank=True)



    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    

# ORDERS
class Order(models.Model):
    STATUS_CHOICES = [
        ('delivered', 'تم التسليم'),
        ('confirmed', 'تم التأكيد'),
        ('canceled', 'ملغي'),
        ('in_progress', 'جاري التوصيل'),
        ('changed', 'تم تغيير الطلبية'),
    ]

    DELIVERY_CHOICES = [
        ('stop_desk', 'المكتب'),
        ('home', 'المنزل'),
    ]
    STATE_CHOICES = [
        ('الشلف', 'الشلف'),
        ('الجزائر', 'الجزائر'),
        ('عين الدفلى', 'عين الدفلى'),
    ]
    product = models.ForeignKey(Product, related_name='apply_order', verbose_name="إسم المنتج", on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name="إسمك الكامل")
    phone = models.IntegerField(verbose_name="رقم الهاتف")
    state = models.CharField(max_length=50, choices=STATE_CHOICES, verbose_name="الولاية")
    city = models.CharField(max_length=50, verbose_name="البلدية")
    order_at = models.DateTimeField(auto_now=True, verbose_name="وقت نشر الطلبية")
    quantity = models.IntegerField(verbose_name="الكمية", null=True, blank=True, default=1, validators=[MinValueValidator(1), MaxValueValidator(100)])
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, null=True, blank=True, verbose_name="الحالة")
    delivery = models.CharField(max_length=50, choices=DELIVERY_CHOICES, null=True, blank=True, verbose_name="نوع التوصيل")

    def __str__(self):
        return self.name

back end/project/app/views.py
from django.shortcuts import render , redirect , HttpResponse
from .models import *
from .form import *
# Create your views here.

def home(request):
    pro = Product.objects.all()
    blog = Blog.objects.all()
    context={
        'pro':pro,
        'blog':blog
    }
    return render(request , 'pages/index.html' ,context)

def products(request):
    pro = Product.objects.all()
    blog = Blog.objects.all()
    context={
        'pro':pro,
        'blog':blog
    }
    return render(request , 'pages/products.html' ,context)


def details(request, slug):
    detail = Product.objects.get(slug=slug)
    # تعيين قيمة افتراضية لـ pro_list
    pro_list = None

    if request.method == 'POST':
        form = OrderForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.product = detail
            myform.save()
            return redirect('stor:index')  # Redirect to the index page after successful form submission
    else:
        form = OrderForm()
        # تعيين قيمة لـ pro_list في الحالة الأخيرة
        pro_list = Product.objects.all()

    context = {
        'det': detail,
        'form': form,
        'pro': pro_list,
    }
    return render(request, 'pages/pro-details.html', context)

def blogs(request):
    blogs = Blog.objects.all()
    context={
        'blog':blogs
    }
    return render(request , 'pages/blogs.html' ,context)


def blog(request, slug):
    detail = Blog.objects.get(slug=slug)
    context = {
        'det': detail,
    }
    return render(request, 'pages/sigle-blog.html', context)

back end/project/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Honey Store</title>
    <!-- CSS Links Start -->
    <link rel="stylesheet" href="{% static './dist/style.css' %}">
    <link rel="stylesheet" href="{% static './dist/index.css' %}">
    <!-- CSS Links End -->

    <!-- icons start -->
    <link rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <!-- icons end -->
     
    <style>
        /* Tailwind CSS custom colors */
        .bg-honey-yellow { background-color: #FFDD57; }
        .text-honey-brown { color: #6B4226; }
        .text-honey-green { color: #355E3B; }
        .bg-honey-amber { background-color: #FFA726; }
        
    </style>
</head>
<body class="bg-white text-honey-brown font-sans">
    {% include "./parts/nav.html" %}

    {% block body %}

    {% endblock body %}
    {% include "./parts/footer.html" %}
<!-- js start -->
<script src="{% static './dist/js/slide-img.js' %}"></script>
<script src="{% static './dist/js/js.js' %}"></script>
<!-- js end -->
</body>
</html>

back end/project/app/templates/pages/about.html
{% extends "base.html" %}
{% load static %}
{% block body %}

  <!-- About Us Section -->
  <section class="container mx-auto py-10 px-3 md:px-0">
    <div class="max-w-4xl mx-auto">
        <h1 class="text-4xl font-bold text-honey-brown mb-6">About Us</h1>
        <p class="text-lg">Honey Company is dedicated to providing the finest honey products directly from nature. We believe in the power of natural ingredients and their numerous benefits for health and well-being.</p>
        <p class="text-lg mt-4">Established in 1990, we have been committed to sourcing honey from the best farms and ensuring that our products maintain the highest quality standards.</p>
        <h2 class="text-2xl font-bold text-honey-brown mt-8">Our Products</h2>
        <ul class="list-disc mt-4 ml-6 text-lg text-honey-green">
            <li>Pure Honey</li>
            <li>Organic Honey</li>
            <li>Wildflower Honey</li>
            <li>Honey Comb</li>
            <li>Honey Infusions</li>
        </ul>
    </div>
</section>{% endblock body %}

back end/project/app/templates/pages/blogs.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <!-- Blog Header -->
    <header class="bg-honey-amber text-center py-32 bg-cover" style="background-image: url({% static './dist/img/hero.jpg' %});">
        <h1 class="text-5xl font-bold text-white">Our Blog</h1>
        <p class="text-white mt-4">Read the latest articles and updates about our honey products</p>
    </header>

    <!-- Blog Posts Section -->
    <section class="container mx-auto py-20">
        <h2 class="text-3xl font-bold text-center">Latest Posts</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-10">
            {% for blog in blog %}
            <!-- Blog Post 1 -->
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <img src="blog1.jpg" alt="Blog Post 1" class="w-full h-48 object-cover rounded-lg">
                <h3 class="text-xl font-bold mt-4 text-honey-brown">{{blog.title}}</h3>
                <p class="mt-2 text-honey-green">{{blog.details}}</p>
                <a href="{% url 'app:blog' blog.slug %}" class="text-honey-yellow font-semibold mt-4 inline-block">Read More</a>
            </div>
            {% endfor %}
            <!-- Add more blog posts as needed -->
        </div>
    </section>

{% endblock body %}

back end/project/app/templates/pages/contact.html
{% extends "base.html" %}
{% load static %}

{% block body %}

    <!-- Contact Us Section -->
    <section class="container mx-auto py-10 px-3 md:px-0">
        <div class="max-w-lg mx-auto">
            <h1 class="text-4xl font-bold text-honey-brown mb-6">Contact Us</h1>
            <form action="#" method="POST" class="space-y-4">
                <div>
                    <label for="name" class="block text-lg text-honey-brown mb-2">Name</label>
                    <input type="text" id="name" name="name" placeholder="Your Name" class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-honey-green" required>
                </div>
                <div>
                    <label for="email" class="block text-lg text-honey-brown mb-2">Email</label>
                    <input type="email" id="email" name="email" placeholder="Your Email" class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-honey-green" required>
                </div>
                <div>
                    <label for="message" class="block text-lg text-honey-brown mb-2">Message</label>
                    <textarea id="message" name="message" rows="5" placeholder="Your Message" class="w-full px-4 py-2 border border-gray-300 rounded-md resize-none focus:outline-none focus:border-honey-green" required></textarea>
                </div>
                <button type="submit" class="bg-honey-amber text-white font-semibold py-2 px-6 rounded-md hover:bg-honey-yellow">Send Message</button>
            </form>
        </div>
    </section>
{% endblock body %}

back end/project/app/templates/pages/index.html
{% extends "base.html" %}
{% load static %}


{% block body %}

    <!-- header start -->
    <header class="flex flex-col md:flex-row justify-around items-center bg-honey-amber text-center bg-cover overflow-hidden" style="background-image: url({% static './dist/img/hero.jpg' %});">
        <div class="flex flex-col items-center justify-center px-10">
            <h1 class="text-5xl font-bold text-honey-green ">Welcome to the Best Honey Store</h1>
        <p class="text-honey-green  mt-4">Discover the finest honey products directly from nature</p>
        <a href="#products" class="text-center mt-8 inline-block text-2xl bg-white text-honey-amber font-semibold px-6 py-3 rounded-full hover:text-white hover:bg-[#355E3B] hover:scale-[1.1] hover:shadow-md hover:shadow-black transition-all w-fit duration-500"><script src="https://cdn.lordicon.com/lordicon.js"></script>
            <lord-icon
                src="https://cdn.lordicon.com/fnsllnpu.json"
                trigger="hover"
                style="width:30px;height:30px">
            </lord-icon>See More</a>
        
        </div>
        <img src="{% static './dist/img/hero1.png' %}" class="animate-spin anima" alt="" style="animation-duration: 30s">
    </header>
    <!-- header end -->


    <!-- Products Section -->
    <section id="products" class="container mx-auto py-10">
        <div class="max-w-4xl mx-auto">
            <h2 class="text-3xl font-bold text-honey-brown mb-6">Our Products</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mt-10">
                {% for product in pro %}
                <div class="bg-white p-6 rounded-lg shadow-lg">
                    <img src="{{ product.img1.url }}" alt="Honey" class="w-full h-48 object-cover rounded-lg">
                    <h3 class="text-xl font-bold mt-4 text-honey-brown">{{product.title}}</h3>
                    <p class="mt-2 text-honey-green">{{product.price}} DA</p>
                    <a href="{% url 'app:details' product.slug %}" class="text-honey-yellow font-semibold mt-4 inline-block">Learn More</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

  <section class="px-2 md:px-20">
      <!-- About Us Section -->
      <section id="about" class="bg-honey-yellow py-10 px-2 md:px-10 rounded-xl mb-10">
        <div class="container">
            <h2 class="text-3xl font-bold text-honey-brown mb-6">About Us</h2>
            <p class="text-lg text-honey-green">Honey Company is dedicated to providing the finest honey products directly from nature. We believe in the power of natural ingredients and their numerous benefits for health and well-being.</p>
        </div>
    </section>

   <!-- Contact Us Section -->
   <section id="contact" class="bg-honey-amber py-10 px-2 md:px-10 rounded-xl mb-10">
    <div class="container mx-auto">
        <h2 class="text-3xl font-bold text-honey-brown mb-6">Contact Us</h2>
        <form action="#" method="POST" class="space-y-4">
            <div>
                <label for="name" class="block text-lg text-honey-brown mb-2">Name</label>
                <input type="text" id="name" name="name" placeholder="Your Name" class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-honey-green" required>
            </div>
            <div>
                <label for="email" class="block text-lg text-honey-brown mb-2">Email</label>
                <input type="email" id="email" name="email" placeholder="Your Email" class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-honey-green" required>
            </div>
            <div>
                <label for="message" class="block text-lg text-honey-brown mb-2">Message</label>
                <textarea id="message" name="message" rows="5" placeholder="Your Message" class="w-full px-4 py-2 border border-gray-300 rounded-md resize-none focus:outline-none focus:border-honey-green" required></textarea>
            </div>
            <button type="submit" class="bg-honey-yellow text-white font-semibold py-2 px-6 rounded-md hover:bg-orange-600 hover:scale-125 transition-all">Send Message</button>
        </form>
    </div>
</section>
  </section>

  {% endblock body %}

back end/project/app/templates/pages/pro-details.html
{% extends "base.html" %}
{% load static %}
{% block body %}


    <!-- Product Details Section -->
    <section class="container mx-auto py-10">
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-10">
            <!-- Product Image -->
            <div class="text-center relative ">
                <div class="slider-container relative l h-[250px] min-h-[200px] md:h-full mx-auto">
                    <div id="salde-number" class="salde-number " style="display: none;">
                       
                    </div>
                    
                        {% if det.img1  %}
                        <img id="1" src="{{ det.img1.url }}"  class="w-full  min-h-[80%] rounded-lg shadow-lg absolute top-0 left-0 opacity-100 transition-opacity duration-1000"  alt="">
                        {% endif %}
                        
                        {% if det.img2 %}
                        <img id="2" src="{{ det.img2.url }}"  class="w-full min-h-[80%] rounded-lg shadow-lg absolute top-0 left-0 opacity-100 transition-opacity duration-1000" alt="">
                        {% endif %}

                        {% if det.img3 %}
                        <img id="4" src="{{ det.img3.url }}"  class="w-full min-h-[80%] rounded-lg shadow-lg absolute top-0 left-0 opacity-100 transition-opacity duration-1000" alt="">
                        {% endif %}
                    <div id="indicators" class="indicator" style="display: none;">
        
                    </div>
                    <button id="prev" class="prev absolute top-[50%] left-1 bg-gray-200 hover:bg-gray-400 rounded-full w-10 h-10 z-50">
                        <i class='bx bx-chevron-left'></i>
                    </button>
                    <button id="next" class="next absolute top-[50%] right-1 bg-gray-200 hover:bg-gray-400 rounded-full w-10 h-10 z-50">
                        <i class='bx bx-chevron-right'></i>
                    </button>
                </div>
            </div>

            <!-- Product Description -->
            <div class="px-4 md:px-0">
                <h2 class="text-3xl font-bold text-honey-brown">{{det.title}}</h2>
                <p class="mt-4 text-honey-green">{{det.price}} DA</p>
                {{det.details|safe}}
            </div>
        </div>
    </section>




{% endblock body %}

back end/project/app/templates/pages/products.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <!-- header start -->
    <header class="bg-honey-amber text-center py-32 bg-cover" style="background-image: url({% static './dist/img/hero.jpg' %});">
        <h1 class="text-5xl font-bold text-honey-green">Honey Store</h1>
        <p class=" mt-4 text-honey-green">Discover the finest honey products directly from nature</p>
        <a href="#product" class="text-center mt-8 inline-block text-2xl bg-white text-honey-amber font-semibold px-6 py-3 rounded-full hover:text-white hover:bg-[#355E3B] hover:scale-[1.1] hover:shadow-md hover:shadow-black transition-all w-fit duration-500"><script src="https://cdn.lordicon.com/lordicon.js"></script>
            <lord-icon
                src="https://cdn.lordicon.com/fnsllnpu.json"
                trigger="hover"
                style="width:25px;height:24px">
            </lord-icon>Shop Now</a>    </header>
    <!-- header end -->

    <!-- content start -->
    <section class="container mx-auto py-20" id="product">
        <h2 class="text-3xl font-bold text-center">Our Products</h2>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mt-10">
            {% for product in pro %}
            <div class="bg-white p-6 rounded-lg shadow-lg">
                <img src="./dist/img/product/1.jpg" alt="Honey" class="w-full h-48 object-cover rounded-lg">
                <h3 class="text-xl font-bold mt-4 text-honey-brown">{{product}}</h3>
                <p class="mt-2 text-honey-green">{{product.details}}</p>
                <a href="{% url "app:details" product.slug %}" class="text-honey-yellow font-semibold mt-4 inline-block">Learn More</a>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- content end -->
    {% endblock body %}

back end/project/app/templates/pages/sigle-blog.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <!-- Article Details -->
    <section class="container mx-auto py-10">
        <div class="max-w-4xl mx-auto">
            <h1 class="text-4xl font-bold text-honey-brown mb-4">{{det.name}}</h1>
            <p class="text-honey-green">Published on {{det.published_at}} by {{det.author}} </p>
            <img src="{{ det.img.url }}" alt="Honey Article" class="w-full rounded-lg shadow-lg mt-6">
            <div class="mt-8">
                {{det.details|safe}}
            </div>
        </div>
    </section>

    {% endblock body %}

back end/project/app/templates/parts/footer.html
 <!-- footer start -->
 <footer class="bg-honey-yellow text-honey-brown py-10 px-10">
    <div class="container mx-auto flex flex-col md:flex-row justify-between items-center">
        <div class="mb-6 md:mb-0">
            <a href="#" class="text-2xl font-bold text-honey-brown">Honey Store</a>
            <p class="mt-2 text-honey-green">Finest honey products directly from nature.</p>
        </div>
        <div class="flex space-x-4">
            <a href="#" class="text-honey-brown hover:text-honey-amber">Home</a>
            <a href="#" class="text-honey-brown hover:text-honey-amber">Products</a>
            <a href="#" class="text-honey-brown hover:text-honey-amber">Blog</a>
            <a href="#" class="text-honey-brown hover:text-honey-amber">About Us</a>
            <a href="#" class="text-honey-brown hover:text-honey-amber">Contact</a>
        </div>
    </div>
    <div class="container mx-auto mt-8 flex justify-center space-x-6">
        <a href="#" class="text-honey-brown hover:text-honey-amber">
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                <!-- أيقونة فيسبوك -->
                <path d="M22.675 0H1.325C0.593 0 0 0.593 0 1.325v21.351C0 23.407 0.593 24 1.325 24H12.82v-9.294H9.692v-3.622h3.128V8.413c0-3.1 1.894-4.785 4.66-4.785 1.325 0 2.464 0.099 2.796 0.143v3.24l-1.918 0.001c-1.504 0-1.795 0.715-1.795 1.763v2.31h3.587l-0.467 3.622h-3.12V24h6.11C23.407 24 24 23.407 24 22.675V1.325C24 0.593 23.407 0 22.675 0z"/>
            </svg>
        </a>
        <a href="#" class="text-honey-brown hover:text-honey-amber">
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                <!-- أيقونة تويتر -->
                <path d="M24 4.557c-0.883 0.392-1.832 0.656-2.828 0.775 1.017-0.611 1.798-1.574 2.165-2.723-0.951 0.564-2.005 0.974-3.127 1.194-0.897-0.956-2.178-1.555-3.594-1.555-2.717 0-4.92 2.203-4.92 4.917 0 0.386 0.044 0.761 0.128 1.122-4.087-0.205-7.713-2.164-10.14-5.144-0.423 0.725-0.666 1.567-0.666 2.465 0 1.701 0.867 3.197 2.187 4.076-0.806-0.026-1.566-0.247-2.229-0.617v0.062c0 2.375 1.689 4.358 3.933 4.805-0.412 0.112-0.846 0.171-1.294 0.171-0.317 0-0.625-0.031-0.927-0.087 0.626 1.956 2.444 3.379 4.6 3.419-1.683 1.319-3.808 2.106-6.115 2.106-0.397 0-0.789-0.023-1.175-0.068 2.18 1.398 4.768 2.213 7.548 2.213 9.057 0 14.009-7.508 14.009-14.009 0-0.213-0.004-0.425-0.013-0.637 0.961-0.694 1.796-1.562 2.457-2.549z"/>
            </svg>
        </a>
        <a href="#" class="text-honey-brown hover:text-honey-amber">
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                <!-- أيقونة إنستغرام -->
                <path d="M12 2.163c3.204 0 3.584 0.012 4.849 0.07 1.259 0.058 2.084 0.264 2.581 0.441 0.631 0.22 1.086 0.485 1.566 0.965 0.48 0.48 0.745 0.935 0.965 1.566 0.177 0.497 0.383 1.322 0.441 2.581 0.058 1.265 0.07 1.645 0.07 4.849s-0.012 3.584-0.07 4.849c-0.058 1.259-0.264 2.084-0.441 2.581-0.22 0.631-0.485 1.086-0.965 1.566-0.48 0.48-0.935 0.745-1.566 0.965-0.497 0.177-1.322 0.383-2.581 0.441-1.265 0.058-1.645 0.07-4.849 0.07s-3.584-0.012-4.849-0.07c-1.259-0.058-2.084-0.264-2.581-0.441-0.631-0.22-1.086-0.485-1.566-0.965-0.48-0.48-0.745-0.935-0.965-1.566-0.177-0.497-0.383-1.322-0.441-2.581-0.058-1.265-0.07-1.645-0.07-4.849s0.012-3.584 0.07-4.849c0.058-1.259 0.264-2.084 0.441-2.581 0.22-0.631 0.485-1.086 0.965-1.566 0.48-0.48 0.935-0.745 1.566-0.965 0.497-0.177 1.322-0.383 2.581-0.441 1.265-0.058 1.645-0.07 4.849-0.07zM12 0c-3.259 0-3.667 0.013-4.947 0.072-1.276 0.059-2.45 0.273-3.334 0.598-0.904 0.333-1.672 0.779-2.436 1.543s-1.21 1.532-1.543 2.436c-0.325 0.884-0.539 2.058-0.598 3.334-0.059 1.28-0.072 1.688-0.072 4.947s0.013 3.667 0.072 4.947c0.059 1.276 0.273 2.45 0.598 3.334 0.333 0.904 0.779 1.672 1.543 2.436s1.532 1.21 2.436 1.543c0.884 0.325 2.058 0.539 3.334 0.598 1.28 0.059 1.688 0.072 4.947 0.072s3.667-0.013 4.947-0.072c1.276-0.059 2.45-0.273 3.334-0.598 0.904-0.333 1.672-0.779 2.436-1.543s1.21-1.532 1.543-2.436c0.325-0.884 0.539-2.058 0.598-3.334 0.059-1.28 0.072-1.688 0.072-4.947s-0.013-3.667-0.072-4.947c-0.059-1.276-0.273-2.45-0.598-3.334-0.333-0.904-0.779-1.672-1.543-2.436s-1.532-1.21-2.436-1.543c-0.884-0.325-2.058-0.539-3.334-0.598-1.28-0.059-1.688-0.072-4.947-0.072z"/>
                <path d="M12 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.162 6.162 6.162 6.162-2.759 6.162-6.162-2.759-6.162-6.162-6.162zM12 15.525c-1.944 0-3.525-1.581-3.525-3.525s1.581-3.525 3.525-3.525 3.525 1.581 3.525 3.525-1.581 3.525-3.525 3.525z"/>
                <circle cx="18.406" cy="5.594" r="1.44"/>
            </svg>
        </a>
    </div>
    <div class="container mx-auto mt-6 text-center">
        <p>&copy; 2024 Honey Store. All rights reserved.</p>
    </div>
</footer>

back end/project/app/templates/parts/nav.html
<!-- nav-bar start -->
<nav class="bg-honey-yellow p-4 shadow-lg z-50 opacity-100">
    <div class="container mx-auto flex justify-between relative  text-center ">
        <a href="#" class="text-honey-brown text-2xl font-bold">Honey Store</a>
        <div class="hidden md:flex">
            <a href="./index.html" class="text-honey-brown mx-2 text-center">Home</a>
            <a href="./products.html" class="text-honey-brown mx-2">Products</a>
            <a href="./blogs.html" class="text-honey-brown mx-2">Blog</a>
            <a href="./about.html" class="text-honey-brown mx-2">About Us</a>
            <a href="./contact.html" class="text-honey-brown mx-2">Contact</a>
        </div>
        <div class="flex flex-col absolute z-10  w-full text-center top-[-400px] bg-honey-yellow  transition-all duration-500 berger">
            <a href="./index.html" class="text-honey-brown mx-2 text-center">Home</a>
            <a href="./products.html" class="text-honey-brown mx-2">Products</a>
            <a href="./blogs.html" class="text-honey-brown mx-2">Blog</a>
            <a href="./about.html" class="text-honey-brown mx-2">About Us</a>
            <a href="./contact.html" class="text-honey-brown mx-2">Contact</a>
        </div>
        <button class="flex md:hidden" name="menu" onclick="Menu(this)"><i class='bx bx-menu text-2xl text-center'></i></button>
    </div>
    <script>
        function Menu(e){
          let list = document.querySelector('.berger');
          e.name === 'menu' ? (e.name = "close",list.classList.add('top-[45px]') , list.classList.add('opacity-100')) :( e.name = "menu" ,list.classList.remove('top-[45px]'),list.classList.remove('opacity-100'))
        }
      </script>
</nav>
<!-- nav-bar end -->